### PR TITLE
udpate docs with config page

### PR DESCRIPTION
**Pull request by tessalt**
adds a new /configuration page to the docs with a crazy huge table of ALL the possible config options. No matter what we do with the docs, we can link to this table whenever we're like "and you can find all the options here" 

added some bad css, sorry. 

@harisaurus @michelleyschen

### CODE REVIEW

**Comment by michelleyschen** [comment]
This may be a stupid question, but do you guy/gal know if this file can be view as actual webpage on github or I will have to checkout the branch?

**Comment by tessalt** [comment]
you'll have to check out the branch, and run `npm run docs` then visit localhost:4000/buy-button-js/configuration/

**Comment by michelleyschen** [comment]
Thank you! #LearnSomethingNewEveryday

**Comment by michelleyschen** [comment]
right this also mean I need to install jekyll. Do you think we should included this in the devDependency?

**Comment by harisaurus** [comment]
@michelleyschen yeah its a gem, so `gem install jekyll` should suffice to install what you need and `npm run docs` will take care of running the server etc for you

**Comment by michelleyschen** [comment]
@tessalt your review as PR
https://github.com/Shopify/buy-button-js/pull/347
Cheers!

**Pull request merged**
